### ISSUE TITLE
Vamo embelezar esse git ae

### ISSUE THREAD

**Issue by Kur1sutaru** [ldiass/MPSbase#1]
Acho que tu poderia fazer a Wiki do AutoGO e colocar o link do MPSBase, se quiser posso te ajudar.

**Comment by jvfe** [comment]
Apoio! O projeto que vocês realizaram é muito bom, muito bom mesmo. Tem que dar uma documentada pra espalhar esse conhecimento e ficar mais acessível pra quem achar ele no futuro. 

Um ponto inicial é já deixar no README uma informação legal sobre o que é o projeto, talvez trazendo um exemplo do uso.

Parabéns pra vocês dois!

**Comment by Kur1sutaru** [comment]
melhorar o readme e a documentação do pacote
